[package]
name = "clinical_scrubber"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
once_cell = "1"
unicode-normalization = "0.1"
clap = { version = "4.5", features = ["derive"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
